#!/usr/bin/env bash
# bump-openclaw.sh — Pin nix-openclaw to a tagged release of openclaw/openclaw.
#
# Usage:
#   ./bump-openclaw.sh v2026.3.7        # specific tag
#   ./bump-openclaw.sh                   # latest release
#
# This script:
#   1. Resolves the tag → commit SHA via GitHub API
#   2. Prefetches the source tarball hash (nix-prefetch-url)
#   3. Writes openclaw-source.nix with a fake pnpmDepsHash
#   4. Attempts a flake build to discover the real pnpmDepsHash
#   5. Rewrites openclaw-source.nix with the correct hash
#
# Requires: curl, jq, nix, sed
# Must be run from the nix-openclaw repo root.

set -euo pipefail

REPO="openclaw/openclaw"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SOURCE_NIX="$SCRIPT_DIR/nix/sources/openclaw-source.nix"

# Resolve tag
if [ -n "${1:-}" ]; then
  TAG="$1"
else
  echo "Fetching latest release tag..."
  TAG=$(curl -sf "https://api.github.com/repos/$REPO/releases/latest" | jq -r '.tag_name')
  echo "Latest release: $TAG"
fi

# Strip leading 'v' for version string
VERSION="${TAG#v}"

echo "Resolving $TAG → commit..."
REV=$(curl -sf "https://api.github.com/repos/$REPO/git/ref/tags/$TAG" | jq -r '
  if .object.type == "tag" then .object.url
  elif .object.type == "commit" then .object.sha
  else empty end
')

# Handle annotated tags (need to dereference)
if [[ "$REV" == http* ]]; then
  REV=$(curl -sf "$REV" | jq -r '.object.sha')
fi

echo "Commit: $REV"

# Prefetch source hash
echo "Prefetching source tarball..."
TARBALL_URL="https://github.com/$REPO/archive/$REV.tar.gz"
SRC_HASH=$(nix-prefetch-url --unpack "$TARBALL_URL" 2>/dev/null)
SRC_HASH_SRI=$(nix hash convert --hash-algo sha256 --to sri "$SRC_HASH")
echo "Source hash: $SRC_HASH_SRI"

write_source_nix() {
  local pnpm_hash="$1"
  cat > "$SOURCE_NIX" << EOF
# Pinned OpenClaw source for nix-openclaw
# Generated by bump-openclaw.sh — do not edit manually
{
  owner = "openclaw";
  repo = "openclaw";
  rev = "$REV";
  # version: derived from git tag $TAG
  version = "$VERSION";
  hash = "$SRC_HASH_SRI";
  pnpmDepsHash = "$pnpm_hash";
}
EOF
}

# Phase 1: write with fake pnpmDepsHash
FAKE_HASH="sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
echo ""
echo "Phase 1: Writing openclaw-source.nix with placeholder pnpm hash..."
write_source_nix "$FAKE_HASH"

# Phase 2: build to discover real hash
echo "Phase 2: Building to discover pnpm deps hash (this takes a while)..."
echo "  Running: nix build $SCRIPT_DIR#packages.x86_64-linux.openclaw-gateway"
echo ""

PNPM_HASH=""
BUILD_OUTPUT=$(nix build "$SCRIPT_DIR#packages.x86_64-linux.openclaw-gateway" --no-link 2>&1) || {
  # Extract the "got:" hash from the mismatch error
  PNPM_HASH=$(echo "$BUILD_OUTPUT" | grep -oP 'got:\s+\Ksha256-\S+' | head -1)
  if [ -z "$PNPM_HASH" ]; then
    echo "ERROR: Build failed but couldn't extract pnpm deps hash from output."
    echo ""
    echo "Build output:"
    echo "$BUILD_OUTPUT" | tail -30
    echo ""
    echo "openclaw-source.nix has been written with a placeholder hash."
    echo "Run 'nix build' manually, find the 'got: sha256-...' line, and update pnpmDepsHash."
    exit 1
  fi
}

if [ -z "$PNPM_HASH" ]; then
  echo "ERROR: Build succeeded with fake hash — that shouldn't happen."
  echo "The pnpmDepsHash may not be checked. Leaving placeholder in place."
  exit 1
fi

echo "pnpm deps hash: $PNPM_HASH"

# Phase 3: rewrite with real hash
echo ""
echo "Phase 3: Rewriting openclaw-source.nix with correct hash..."
write_source_nix "$PNPM_HASH"

# Phase 4: verify build
echo ""
echo "Phase 4: Verification build..."
if nix build "$SCRIPT_DIR#packages.x86_64-linux.openclaw-gateway" --no-link 2>&1; then
  echo ""
  echo "✅ Build succeeded!"
else
  echo ""
  echo "⚠️  Verification build failed. Check the output above."
  exit 1
fi

echo ""
echo "Updated $SOURCE_NIX"
echo "   Tag:     $TAG"
echo "   Version: $VERSION"
echo "   Commit:  $REV"
echo ""
echo "Next steps:"
echo "  1. git add nix/sources/openclaw-source.nix && git commit && git push"
echo "  2. In nix-config: nix flake update nix-openclaw && make build-openclaw"
echo "  3. make switch-openclaw to deploy"
