# Pinned OpenClaw source for nix-openclaw
# Generated by bump-openclaw.sh — do not edit manually
{
  owner = "openclaw";
  repo = "openclaw";
  rev = "3caab9260cb0a0064e6a37b2de3bedc8a547e599";
  # version: derived from git tag v2026.3.8
  version = "2026.3.8";
  hash = "sha256-PeNbusrYqB0yn+t8BERFr9E1YYpuWaw0w+YTzPFQgo8=";
  pnpmDepsHash = "sha256-CpgulfZfN1yHXpXBR1wvsSaME8y9ZX+dQQ4JJjp3PRs=";
}
